/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Kisan
 */
public class dibujo extends javax.swing.JFrame {

    /**
     * Creates new form dibujo
     */
    private Graph graph;
    private javax.swing.JTextArea textArea;
    private javax.swing.JScrollPane scrollPane;
    
    public dibujo() {
        initComponents();
        initGraph();
        drawGraph();
        textArea = new javax.swing.JTextArea();
        textArea.setColumns(20);
        textArea.setRows(5);
        scrollPane = new javax.swing.JScrollPane(textArea);

        // Añadir el scrollPane al layout de la ventana principal
        getContentPane().add(scrollPane, java.awt.BorderLayout.SOUTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelito = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Corto = new javax.swing.JButton();
        Largo = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelito.setBackground(new java.awt.Color(204, 255, 255));
        panelito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelitoLayout = new javax.swing.GroupLayout(panelito);
        panelito.setLayout(panelitoLayout);
        panelitoLayout.setHorizontalGroup(
            panelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelitoLayout.setVerticalGroup(
            panelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        jButton1.setText("Matriz de Adyacencia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Corto.setText("Camino más Corto");
        Corto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CortoActionPerformed(evt);
            }
        });

        Largo.setText("Camino más largo");
        Largo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LargoActionPerformed(evt);
            }
        });

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Anchura");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Profundidad");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(Corto)
                        .addGap(18, 18, 18)
                        .addComponent(Largo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Corto)
                    .addComponent(Largo)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int[][] adjacencyMatrix = graph.getAdjacencyMatrix();
    JPanel matrixPanel = new JPanel(new GridLayout(adjacencyMatrix.length + 1, adjacencyMatrix.length + 1));
    matrixPanel.add(new JLabel(" "));
    for (int i = 1; i <= adjacencyMatrix.length; i++) {
        matrixPanel.add(new JLabel(Integer.toString(i)));
    }
    for (int i = 0; i < adjacencyMatrix.length; i++) {
        matrixPanel.add(new JLabel(Integer.toString(i + 1)));
        for (int j = 0; j < adjacencyMatrix[i].length; j++) {
            matrixPanel.add(new JLabel(Integer.toString(adjacencyMatrix[i][j])));
        }
    }

    JFrame frame = new JFrame("Matriz de Adyacencia");
    frame.add(matrixPanel);
    frame.pack();
    frame.setSize(600, 600);
    frame.setVisible(true);
}                                        

private void unused(int[][] matrix) {
    System.out.println("Matriz de adyacencia:");
    for (int[] row : matrix) {
        for (int val : row) {
            System.out.print(val + " ");
        }
        System.out.println();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CortoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CortoActionPerformed
        String message = graph.CaminoCorto(1, 9);
        showMessageDialog(message);
    }//GEN-LAST:event_CortoActionPerformed

    private void LargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LargoActionPerformed
        String message = graph.CaminoLargo(1, 9);
        showMessageDialog(message);
    }//GEN-LAST:event_LargoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        List<Integer> bfsResult = graph.recorridoAnchura(1);
        showMessageDialog("Recorrido por Anchura: " + bfsResult);   
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        List<Integer> dfsResult = graph.recorridoProfundidad(1);
        showMessageDialog("Recorrido por Profundidad: " + dfsResult);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void showMessageDialog(String message) {
    JOptionPane.showMessageDialog(this, message, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dibujo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dibujo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Corto;
    private javax.swing.JButton Largo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel panelito;
    // End of variables declaration//GEN-END:variables

    private void initGraph() {
    graph = new Graph();
        // Añadir aristas al grafo (según la imagen proporcionada)
        graph.addEdge(1, 2, 1);
        graph.addEdge(1, 3, 2);
        graph.addEdge(2, 4, 3);
        graph.addEdge(2, 3, 1);
        graph.addEdge(2, 5, 2);
        graph.addEdge(3, 5, 2);
        graph.addEdge(3, 4, 2);
        graph.addEdge(4, 6, 3);
        graph.addEdge(4, 7, 5);
        graph.addEdge(6, 5, 1);
        graph.addEdge(5, 4, 3);
        graph.addEdge(6, 7, 1);
        graph.addEdge(6, 8, 2);
        graph.addEdge(7, 9, 1);
        graph.addEdge(8, 6, 2);
        graph.addEdge(8, 9, 5);
        graph.addEdge(8, 7, 3);
        graph.addEdge(9, 7, 5);
    }

    private void drawGraph() {
        Funciones graphVisualization = new Funciones(graph);
        panelito.setLayout(new BorderLayout());
        panelito.add(graphVisualization, BorderLayout.CENTER);
        panelito.revalidate();
        panelito.repaint();
    }
}
